// User Reducer Types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const SET_USER = 'SET_USER'
export const LOADING_USER = 'LOADING_USER'

// UI Reducer Types
export const SET_ERRORS = 'SET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const LOADING_UI = 'LOADING_UI'
export const OPEN_REVIEW_SCREEN = 'OPEN_REVIEW_SCREEN'
export const CLOSE_REVIEW_SCREEN = 'CLOSE_REVIEW_SCREEN'

// Data Reducer Types
export const SET_POSTS = 'SET_POSTS'

// Flavor Reducer Types
export const SET_UNSELECTED_FLAVORS = 'SET_UNSELECTED_FLAVORS'
export const SET_HIGHLIGHTED_FLAVORS = 'SET_HIGHLIGHTED_FLAVORS'
export const SET_SELECTED_FLAVORS = 'SET_SELECTED_FLAVORS'